# Generated by Django 4.2.7 on 2023-11-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "Sno",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("Sname", models.CharField(max_length=20)),
                ("Ssex", models.CharField(max_length=2)),
                ("Sage", models.IntegerField(max_length=3)),
                ("Sdept", models.CharField(max_length=20)),
            ],
        ),
    ]
