# Generated by Django 4.2.7 on 2023-11-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0002_alter_student_sage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "Cno",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("Cname", models.CharField(max_length=20)),
                ("Cpno", models.CharField(max_length=9)),
                ("Ccredit", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Sno", models.CharField(max_length=9)),
                ("Cno", models.CharField(max_length=9)),
                ("Grade", models.CharField(max_length=3)),
            ],
        ),
    ]
