# Generated by Django 4.2.7 on 2023-11-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0003_course_sc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="Cpno",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="sc",
            name="Cno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="test.course"
            ),
        ),
        migrations.AlterField(
            model_name="sc",
            name="Sno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="test.student"
            ),
        ),
    ]
